Reference:
  species: mm
  genome: /mnt/user/wzd/00.database/15.index_mouse_genome/Mus_musculus.GRCm39.dna.primary_assembly.fa
  annotgtf: /mnt/user/wzd/00.database/16.annot_mouse/Mus_musculus.GRCm39.107.gtf
  annotgff3: /mnt/user/wzd/00.database/16.annot_mouse/Mus_musculus.GRCm39.107.gff3
  bedfile: /mnt/user/wzd/00.database/16.annot_mouse/Mus_musculus.GRCm39.107.bed
  rRNA_bed: /mnt/user/wzd/00.database/16.annot_mouse/GRCm39_GENCODE_VM27_rRNAs.bed
  refFlat: /mnt/user/wzd/00.database/16.annot_mouse/refFlat.txt
  rRNA_interval: /mnt/user/wzd/00.database/rRNA.interval/mm39.rRNA.interval_list
  star_index: /mnt/user/wzd/00.database/15.index_mouse_genome/index_GRCm39_ensemble107.star

SampleYml: /mnt/user/wzd/05.pipeline_dev/pipeline_SAKit_v1.0/config/sample.yml
OUTPATH: /mnt/user/wzd/05.pipeline_dev/temp/result2

Env:
  python_lib: /data/miniforge3/lib/python3.7/site-packages/:/data/apps/cDNA_Cupcake/sequence/:/data/apps/cDNA_Cupcake/cupcake/tofu/
  python3: /mnt/user/wzd/03.biotools/miniforge3/bin/python3
  java: /usr/bin/java

Database:
  disgenet: /mnt/user/wzd/00.database/DisGeNET/curated_gene_disease_associations.tsv
  fusionhubdb: /mnt/user/wzd/00.database/FusionHubDB/Fusionhub_global_summary.txt
  transcript2gene: /mnt/user/wzd/00.database/SIRV_ERCC/gtf_hg38_SIRV_ERCC/gencode.v32.annotation.tr2g_gtf.tsv
  
SoftwareTools:
  index: /mnt/user/wzd/03.biotools/pacbio_smrtlink/smrtlink_v12/smrtcmds/bin/pbindex
  bam2fastq: /mnt/user/wzd/03.biotools/pacbio_smrtlink/smrtlink_v12/smrtcmds/bin/bam2fastq
  minimap2: /mnt/user/wzd/03.biotools/pacbio_smrtlink/smrtlink_v12/smrtcmds/bin/minimap2
  align_sv: /mnt/user/wzd/03.biotools/pacbio_smrtlink/smrtlink_v12/smrtcmds/bin/pbmm2
  pbsv: /mnt/user/wzd/03.biotools/pacbio_smrtlink/smrtlink_v12/smrtcmds/bin/pbsv
  qctool: /mnt/user/wzd/03.biotools/pacbio_smrtlink/smrtlink_v12/smrtcmds/bin/runqc-reports
  rseqc: /mnt/user/wzd/03.biotools/software/RSeQC-5.0.1/build/scripts-3.10
  short_reads_align: /mnt/user/wzd/03.biotools/miniforge3/bin/STAR
  picard: /mnt/user/wzd/03.biotools/software/picard/build/libs/picard.jar
  snpeff: /mnt/user/wzd/03.biotools/software/snpEff
  snpsift: /mnt/user/wzd/03.biotools/software/snpEff
  vardict: /mnt/user/wzd/03.biotools/software/VarDict-1.8.1
  samtools: /mnt/user/wzd/03.biotools/pacbio_smrtlink/smrtlink_v12/smrtcmds/bin/samtools

ScriptTools:
  sqanti_qc: /mnt/user/wzd/03.biotools/software/SQANTI3-4.2/sqanti3_qc.py
  sqanti_filter: /mnt/user/wzd/03.biotools/software/SQANTI3-4.2/sqanti3_RulesFilter.py
  collapse_isoforms: /mnt/user/wzd/03.biotools/miniforge3/envs/py37/bin/collapse_isoforms_by_sam.py
  get_abundance: /mnt/user/wzd/03.biotools/miniforge3/envs/py37/bin/get_abundance_post_collapse.py
  filter_by_count: /mnt/user/wzd/03.biotools/miniforge3/envs/py37/bin/filter_by_count.py
  filter_away_subset: /mnt/user/wzd/03.biotools/miniforge3/envs/py37/bin/filter_away_subset.py
  fusion_finder: /mnt/user/wzd/03.biotools/miniforge3/envs/py37/bin/fusion_finder.py
  fusion_collate_info: /mnt/user/wzd/03.biotools/miniforge3/envs/py37/bin/fusion_collate_info.py
  
InhouseScript:
  iosform_attibution: /mnt/user/wzd/05.pipeline_dev/pipeline_SAKit_v1.0/workflow/scripts/iosform_attibution.py
  mutation_filter: /mnt/user/wzd/05.pipeline_dev/pipeline_SAKit_v1.0/workflow/scripts/mutation_filter.py
  fusion_annotation: /mnt/user/wzd/05.pipeline_dev/pipeline_SAKit_v1.0/workflow/scripts/fusion_annotation.py 
  gene_annotation_disease: /mnt/user/wzd/05.pipeline_dev/pipeline_SAKit_v1.0/workflow/scripts/gene_annotation_disease.py
  getcmdtool: /mnt/user/wzd/05.pipeline_dev/pipeline_SAKit_v1.0/workflow/scripts/get_cmd.py

ccs:
  software:
    ccsscript:
    ccstool: /mnt/user/wzd/03.biotools/pacbio_smrtlink/smrtlink_v12/smrtcmds/bin/ccs
    fqtosam: /mnt/user/wzd/03.biotools/software/picard/build/libs/picard.jar
  parameter:
    minpass: 3
    toppass: 60
    minsnr: 2.5
    minlength: 10
    maxlength: 50000
    chunk: 9/9
    minrq: 0.9
    thread: 40
    
demultiplex:
  software:
    limascript:
    limatool: /mnt/user/wzd/03.biotools/pacbio_smrtlink/smrtlink_v12/smrtcmds/bin/lima
  configfile:
    barcodefa: /mnt/user/wzd/02.ResDev/00.config/primer.fa

  parameter:
    libraryDesign:
    readsflankedbyadapter:
    maxscoredbarcode: 0
    maxscoredadapter: 0
    minpass: 0
    minlength: 50
    maxinputlength: 0
    badadapterratio: 0
    minscore: 0
    seqmode: --ccs
    thread: 10
refine:
  software:
    refinetool: /mnt/user/wzd/03.biotools/pacbio_smrtlink/smrtlink_v12/smrtcmds/bin/isoseq3
    refinescript: 
  configfile: 
    primerfa: /mnt/user/wzd/02.ResDev/00.config/primer.fa
  parameter:
    minpolyalength: 20
    requirepolya: 
    minrq: -1
    thread: 10
cluster:
  software:
    clustertool: /mnt/user/wzd/03.biotools/pacbio_smrtlink/smrtlink_v12/smrtcmds/bin/isoseq3
    clusterscript: 
  parameter: 
    poa: 10
    qvs: --use-qvs
    outputpattern: --singletons
    thread: 10
    
align:
  software: /mnt/user/wzd/03.biotools/pacbio_smrtlink/smrtlink_v12/smrtcmds/bin/minimap2
  parameter:
      ax: splice
      secondary: no
      o: -O6,24
      b4: -B4
      uf: -uf
      hard_clip_off: -Y
      
collapse:
  parameter:
    short5: --dun-merge-5-shorter 
    mincov: 0.99 
    miniden: 0.95
    

isoform_filter_bycounts:
  parameter:
    cutoff: 2 
    use_group_count: --dun_use_group_count

PBsvParam:
  min_ref_span: 50
  call_min_read_perc_one_sample: 0
